---
title: "Promise"
tags:
  - promise
  - resolve
  - reject
  - then
  - catch
---

- Promise란  
  콜백 지옥을 해결하기 위해서 나온것이 promise이다.  
  promise는 javascript 비동기 처리에 사용되는 객체로서, 콜백함수로 처리하던 구조에서 `new Promise(), resolve(), reject(), .then()`과 같은 promise API를 사용하는 구조이다.  

- promise의 3가지 상태  
  + **pending(대기)**: 비동기 처리 로직이 **아직 완료되지 않은** 상태  
    `new Promise()` 메소드를 호출하면 pending 상태가 된다.  
    메소드를 호출할 때 콜백함수를 선언할 수 있고, 콜백함수의 인자는 `resolve`, `reject` 이다.  
    
    ```
    new Promise(function(resolve, reject){

    });
    ```
    <br>
    
  + **fulfilled(이행)**: 비동기 처리가 완료되어 promise가 **결과 값을 반환**해준 상태  
    pending 상태에서 `resolve`를 실행하면 fulfilled 상태가 된다.  
    
    ```
    new Promise(function(resolve, reject){
      resolve();
    });
    ```
    <br>

    그리고 fulfilled 상태가 되면 `then()`을 사용해서 처리 결과값을 받을 수 있다.  
    
    ```
    function getData() {
      return new Promise(function(resolve, reject) {
        var data = 100;
        resolve(data);
      });
    }

    // resolve()의 결과 값 data를 resolvedData로 받음
    getData().then(function(resolvedData) {
      console.log(resolvedData); // 100
    });
    ```
    <br>

  + **rejected(실패)**: 비동기 처리가 **실패**하거나 **오류가 발생**한 상태  
    pending 상태에서 resolve가 아닌 `reject`를 실행하면 rejected 상태가 된다.  
    그리고 rejected 상태가 되면 실패 결과값을 `catch`를 사용해서 받는다.  
    
    ```
    function getData() {
      return new Promise(function(resolve, reject) {
        reject(new Error("Request is failed"));
      });
    }

    // reject()의 결과 값 Error를 err에 받음
    getData().then().catch(function(err) {
      console.log(err); // Error: Request is failed
    });
    ```
    <br>

  이제 이들을 합쳐서 하나의 예제를 만들어 보자.  
  
  ```
  function getData() {
    return new Promise(function(resolve, reject) {
      $.get('url 주소/products/1', function(response) {
        if (response) {
          resolve(response);
        }
        reject(new Error("Request is failed"));
      });
    });
  }

  // 위 $.get() 호출 결과에 따라 'response' 또는 'Error' 출력
  getData().then(function(data) {
    console.log(data); // 응답을 받아오면 response 값 출력
  }).catch(function(err) {
    console.error(err); // 응답이 없으면 Error 출력
  });
  ```

  서버에서 제대로 응답을 받아오면 resolve를 호출하고, 응답이 없으면 reject를 호출한다. 호출된 메소드에 따라 then이나 catch로 분기하여 응답 결과 혹은 오류를 출력한다.  
  <br>

- Promise Chaining(프로미스 체이닝)  
  promise의 또다른 특징은 여러개의 promise를 연결할 수 있다는 것이다.  
  다음과 같이 promise를 `then`을 사용해서 연결할 수 있다.  

  ```
  function getData() {
    return new Promise({
      // ...
    });
  }

  // then() 으로 여러 개의 프로미스를 연결한 형식
  getData()
    .then(function(data) {
      // ...
    })
    .then(function() {
      // ...
    })
    .then(function() {
      // ...
    });
  ```
  <br>

  그렇다면 이번에는 setTimeout의 예시를 보도록 하자.  

  ```
  new Promise(function(resolve, reject){
    setTimeout(function() {
      resolve(1);
    }, 2000);
  })
  .then(function(result) {
    console.log(result); // 1
    return result + 10;
  })
  .then(function(result) {
    console.log(result); // 11
    return result + 20;
  })
  .then(function(result) {
    console.log(result); // 31
  });
  ```

  promise객체를 하나 생성하고 setTimeout()을 실행하여 2초 후에 resolve()를 실행하는 코드이다.  
  resolve()가 호출되면 pending 상태에서 fulfilled 상태로 넘어가고, then()이 실행된다.  
  첫번째 then에서 result는 1이 출력되고, 그 result에 10을 더하여 리턴한다.  
  그리고 그 다음 then에서 그 값을 이어받아 result를 출력하고 20을 더하여 리턴한다.  
  그리고 또 다음 then에서 마찬가지로 이어받아 최종 result인 31을 출력하게 된다.  

async await은 다음시간에...
